import Head from "next/head";
import CitySearch from "@/components/CitySearch";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ background : "#1d2433" , height: "100vh"}}>
          <div className="container">
            <CitySearch />
          </div>
        </div>
      </main>
    </>
  );
}
